#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 

bspc config border_radius		10
bspc config border_width         2
bspc config window_gap          30
bspc config focused_border_color "#704d0d"

bspc config split_ratio          0.5
bspc config borderless_monocle   true

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop=III state=monocle follow=on
bspc rule -a libreoffice desktop=III state=monocle follow=on
bspc rule -a thunderbird desktop=III state=monocle follow=on
bspc rule -a Ulauncher border=off focus=on  #state=floating

bspc rule -a android-studio state=floating border=off follow=on
bspc rule -a jetbrains-studio state=floating border=off follow=on

#run additional components
exec ~/.config/environmentrc > ~/.config/Environment.log 2>&1
